[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python sticker_bot.py"

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 
